### ISSUE TITLE
Crashes game with optimization mods

### ISSUE THREAD

**Issue by BotiBoster** [b3spectacled/custom-stars#6]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2021-01-06 12:44:32 BOT
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
    at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7)
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
    at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
    at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
    at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:541)
    at net.minecraft.client.main.Main.main(Main:177)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [custom_stars.mixins.json:MixinWorldRenderer] from phase [DEFAULT] in config [custom_stars.mixins.json] FAILED during APPLY
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
    ... 15 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_761::modifyStarColor with priority 1 cannot inject into net/minecraft/class_761::method_3257(Lnet/minecraft/class_4587;F)V merged by thallium.fabric.mixins.general.MixinWorldRenderer with priority 1000 [PREINJECT Applicator Phase -> custom_stars.mixins.json:MixinWorldRenderer -> Prepare Injections ->  -> redirect$zbg000$modifyStarColor(FFFF)V -> Prepare]
    at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.7)
    at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
    at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
    at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375)
    at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255)
    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
    at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
    ... 15 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Initialization --

-- System Details --
  Minecraft Version: 1.16.4
  Minecraft Version ID: 1.16.4
  Operating System: Windows 8 (amd64) version 6.2
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1037433256 bytes (989 MB) / 1845493760 bytes (1760 MB) up to 5368709120 bytes (5120 MB)
  CPUs: 12
  JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  Suspected Mods: Fabric Loader (fabricloader)
  Fabric Mods: angerable-patch: Angerable Patch 1.1.0-1.16.4
               architectury: Architectury 1.2.68
               artifice: Artifice 0.13.1+1.16.2-rc1
               autoconfig1u: Auto Config v1 Updated 3.3.1
               autoconfigtoml: AutoConfig-TOML 1.0.0-fabric
               bettercaves: YUNG's Better Caves 1.16.2-1.0.3
               betterdroppeditems: Better Dropped Items 1.2.4-1.16.2
               bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0
               byg: BYG 1.1.3
               cinderscapes: Cinderscapes 1.3.0+build.51
               cleancut: CleanCut mc1.16-2.1-fabric
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.4.9
               cloth-config2: Cloth Config v4 4.8.3
               colormatic: Colormatic 2.2.7+mc.1.16.3
               com_electronwill_night-config_core: core 3.6.3
               com_electronwill_night-config_toml: toml 3.6.3
               customstars: Custom Stars 0.4.1
               dark-loading-screen: Dark Loading Screen 1.5.0
               earthtojavamobs: Earth2Java 1.5.0+1.16.4
               fabric: Fabric API 0.29.3+1.16
               fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
               fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
               fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
               fabric-commands-v0: Fabric Commands (v0) 0.2.1+cbe9176f3a
               fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
               fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
               fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.2+8004b36d3a
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.5+cbe9176f3a
               fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.2+cbe9176f3a
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
               fabric-models-v0: Fabric Models (v0) 0.2.0+cbe9176f3a
               fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
               fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
               fabric-particles-v1: Fabric Particles (v1) 0.2.3+cbe9176f3a
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.0+cbe9176f3a
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
               fabric-rendering-v1: Fabric Rendering (v1) 1.5.0+c26373133a
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.1+0d4d7e343a
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
               fabric-structure-api-v1: Fabric Structure API (v1) 1.1.3+cbe9176f3a
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
               fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
               fabrication: Fabrication 1.2.8
               fabricloader: Fabric Loader 0.10.8
               falling_tree: FallingTree 2.8.1
               fallingleaves: Falling Leaves 1.3
               firstperson: FirstpersonModel 1.3.0
               illuminations: Illuminations 1.4
               infinityfix: Infinity Fix 1.1.0
               itemmodelfix: Item Model Fix 0.2.4
               lambdynlights: LambDynamicLights 1.3.2+1.16.4
               libstructure: LibStructure 1.5
               lightoverlay: Light Overlay 5.6.1
               lithium: Lithium 0.6.0
               lithium-api: Lithium API 0.6.0
               loadcatcher: Entrypoint Catcher 2.0.0
               mcdw: MC Dungeons Weapons 2.3.5
               minecraft: Minecraft 1.16.4
               mm: Manningham Mills 2.1
               modmenu: Mod Menu 1.14.13+build.19
               mostructures: Mo' Structures 1.0.1+mc.1.16.4
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.4
               org_codehaus_groovy_groovy: groovy 3.0.3
               org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
               phosphor: Phosphor 0.7.0+build.10
               randompatches: RandomPatches 2.1.6-fabric
               reach-entity-attributes: Reach Entity Attribute 1.0.1
               repurposed_structures: Repurposed Structures 1.16.4-1.7.3
               roughlyenoughitems: Roughly Enough Items 5.8.10
               roughlyenoughitems-api: REI (API) 5.8.10
               roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.10
               roughlyenoughitems-runtime: REI (Runtime) 5.8.10
               rpg-hud: RPG-Hud 3.8.1
               slight-gui-modifications: 'Slight' GUI Modifications 1.6.1
               smoothboot: Smooth Boot 1.16.4-1.4.0
               sodium: Sodium 0.1.0
               spruceui: SpruceUI 1.6.4
               terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.0+build.1
               terraform-config-api-v1: Terraform Config API (v1) 1.0.0+build.1
               terraform-dirt-api-v1: Terraform Dirt API (v1) 1.0.0+build.1
               terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.0+build.1
               terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.0+build.1
               terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.0+build.1
               terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.2
               terraform-wood-api-v1: Terraform Wood API (v1) 1.0.0+build.1
               terrestria: Terrestria 2.1.5+build.28
               thallium: Thallium 1.10
               tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
               traverse: Traverse 3.2.0+build.17
               unearthed: Unearthed 1.0.5
               upstream: Upstream 1.0.1
               voyager: Voyager 1.0.0
               waila: Hwyla 1.9.22
               wi_zoom: WI Zoom 1.3-MC1.16.4
               xaerobetterpvp: Better PVP Mod 20.30.0
               xaeroworldmap: Xaero's World Map 1.11.6
               yungsapi: YUNG's API 1.16.4-Fabric-1
  Launched Version: fabric-loader-0.10.8-1.16.4
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: GeForce GTX 1660 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 460.89, NVIDIA Corporation
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  CPU: 12x Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz

**Comment by b3spectacled** [comment]
Thanks, the mod conflict appears to be caused by Thallium.  Unfortunately, I don't think I can much right now as the Thallium source has not been updated (for several months) for the latest version.

**Comment by BotiBoster** [comment]
Well it updated today but don't know if the code changed

**Comment by b3spectacled** [comment]
Ah, I saw that.  It does appear that Thallium itself has a bit of a controversial history due to misleading claims and code theft (probably why the source has been archived) and because of that I will probably not fix the issue for it.  If you still get conflicts with other mods, please let me know!  Thanks.
